name: APK Diff

on:
  pull_request:  
  push:
    branches:
    - 'main'
    - '4.**'
    - '5.**'


permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: write # to comment on PR

jobs:
  assemble-base:
    if: ${{ github.repository != 'signalapp/Signal-Android' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        ref: ${{ github.event.pull_request.base.sha }}

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: ./gradlew assemblePlayProdRelease --parallel

    - name: Copy base apk
      if: steps.cache-base.outputs.cache-hit != 'true'
      run: mv app/build/outputs/apk/playProd/release/*arm64*.apk signal-7.0.0.apk

    - uses: actions/upload-artifact@v3
      with:
        name: signal-7.0.0.apk
        path: signal-7.0.0.apk
